---
apiVersion: v1
kind: Template
metadata:
  name: nise-populator

objects:
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "ubi7-python36"
  spec:
    dockerImageRepository: "registry.access.redhat.com/ubi7/python-36"

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}
    annotations:
      description: "Keeps track of changes in the application image"
  spec:
    lookupPolicy:
      local: true

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      name: ${NAME}
    name: ${NAME}
  spec:
    failedBuildsHistoryLimit: 1
    successfulBuildsHistoryLimit: 2
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    resources:
      requests:
        memory: ${BUILD_MEMORY_REQUEST}
        cpu: ${BUILD_CPU_REQUEST}
      limits:
        memory: ${BUILD_MEMORY_LIMIT}
        cpu: ${BUILD_CPU_LIMIT}
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: PIP_INDEX_URL
            value: ${PIP_INDEX_URL}
          - name: PIPENV_PYPI_MIRROR
            value: ${PIPENV_PYPI_MIRROR}
          - name: ENABLE_PIPENV
            value: "true"
          - name: UPGRADE_PIP_TO_LATEST
            value: "true"
        from:
          kind: ImageStreamTag
          name: ubi7-python36:latest
          namespace: ${NAMESPACE}
        forcePull: true
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub

- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: ${NAME}
    annotations:
      template.openshift.io/expose-aws_access_key_id: "{.data['aws-access-key-id']}"
      template.openshift.io/expose-aws_secret_access_key: "{.data['aws-secret-access-key']}"
      template.openshift.io/expose-azure_storage_account: "{.data['azure-storage-account']}"
      template.openshift.io/expose-azure_storage_connection_string: "{.data['azure-storage-connection-string']}"
      template.openshift.io/expose-insights_url: "{.data['insights-url']}"
      template.openshift.io/expose-insights_user: "{.data['insights-user']}"
      template.openshift.io/expose-insights_password: "{.data['insights-password']}"
      template.openshift.io/expose-insights_account: "{.data['insights-account']}"
      template.openshift.io/expose-insights_org_id: "{.data['insights-org-id']}"
    name: ${NAME}-secret
  stringData:
    aws-access-key-id: ${AWS_ACCESS_KEY_ID}
    aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    azure-storage-account: ${AZURE_STORAGE_ACCOUNT}
    azure-storage-connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    insights-url: ${INSIGHTS_URL}
    insights-user: ${INSIGHTS_USER}
    insights-password: ${INSIGHTS_PASSWORD}
    insights-account: ${INSIGHTS_ACCOUNT_ID}
    insights-org-id: ${INSIGHTS_ORG_ID}

- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: ${NAME}
  spec:
    schedule: "0 2 * * *"
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: nise-populator
              image: nise-populator
              command: ["python", "nise-populator/app.py"]
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: aws-access-key-id
                      name: ${NAME}-secret
                      optional: false
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: aws-secret-access-key
                      name: ${NAME}-secret
                      optional: false
                - name: AZURE_STORAGE_ACCOUNT
                  valueFrom:
                    secretKeyRef:
                      key: azure-storage-account
                      name: ${NAME}-secret
                      optional: false
                - name: AZURE_STORAGE_CONNECTION_STRING
                  valueFrom:
                    secretKeyRef:
                      key: azure-storage-connection-string
                      name: ${NAME}-secret
                      optional: false
                - name: INSIGHTS_URL
                  valueFrom:
                    secretKeyRef:
                      key: insights-url
                      name: ${NAME}-secret
                      optional: false
                - name: INSIGHTS_USER
                  valueFrom:
                    secretKeyRef:
                      key: insights-user
                      name: ${NAME}-secret
                      optional: false
                - name: INSIGHTS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: insights-password
                      name: ${NAME}-secret
                      optional: false
                - name: INSIGHTS_ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      key: insights-account
                      name: ${NAME}-secret
                      optional: false
                - name: INSIGHTS_ORG_ID
                  valueFrom:
                    secretKeyRef:
                      key: insights-org-id
                      name: ${NAME}-secret
                      optional: false
            restartPolicy: OnFailure

parameters:
- description: The name assigned to all frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: nise-populator
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: koku
- description: Initial amount of memory the build container will request.
  displayName: Build Memory Request
  name: BUILD_MEMORY_REQUEST
  required: true
  value: 1Gi
- description: Maximum amount of memory the build container can use.
  displayName: Build Memory Limit
  name: BUILD_MEMORY_LIMIT
  required: true
  value: 1Gi
- description: Initial amount of CPU the build container will request.
  displayName: Build CPU Request
  name: BUILD_CPU_REQUEST
  required: true
  value: 500m
- description: Maximum amount of CPU the build container can use.
  displayName: Build CPU Limit
  name: BUILD_CPU_LIMIT
  required: true
  value: '1'
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Context Directory
  name: CONTEXT_DIR
  required: false
- description: The custom PyPi index URL
  displayName: Custom PyPi Index URL
  name: PIP_INDEX_URL
  required: false
- description: The custom PipEnv PyPi index URL
  displayName: Custom PipEnv PyPi Index URL
  name: PIPENV_PYPI_MIRROR
  required: false
- description: Github trigger secret.  A difficult to guess string encoded as part
    of the webhook URL.  Not encrypted.
  displayName: GitHub Webhook Secret
  value: webh00k
  name: GITHUB_WEBHOOK_SECRET
  required: True
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/project-koku/nise-populator.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
  required: false
  value: master
- displayName: AWS Access Key
  name: AWS_ACCESS_KEY_ID
  required: true
- displayName: AWS Access Secret Key
  name: AWS_SECRET_ACCESS_KEY
  required: true
- displayName: Azure Storage Account
  name: AZURE_STORAGE_ACCOUNT
  required: true
- displayName: Azure Storage Connection String
  name: AZURE_STORAGE_CONNECTION_STRING
  required: true
- displayName: Insights Platform URL
  name: INSIGHTS_URL
  required: true
- displayName: Insights User
  name: INSIGHTS_USER
  required: true
- displayName: Insights Password
  name: INSIGHTS_PASSWORD
  required: true
- displayName: Insights Account ID
  name: INSIGHTS_ACCOUNT_ID
- displayName: Insights Organization ID
  name: INSIGHTS_ORG_ID
